### ISSUE TITLE
Packager doesn't work with macOS Big Sur 11.6

### ISSUE THREAD

**Issue by ShimYama** [shaka-project/shaka-packager#1410]
## System info
**Operating System**: macOS Big Sur 11.6 (MacBook Pro 2016)
**Shaka Packager Version**: v3.2.0

## Issue and steps to reproduce the problem

**Packager Command**: packager-osx-x64 -version

> What is the expected result?
Show version

> What happens instead?
Following error message appeared.
```
dyld: Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE
  Referenced from: /Users/betatest/Downloads/./packager-osx-x64 (which was built for Mac OS X 13.6)
  Expected in: /usr/lib/libc++.1.dylib
 in /Users/betatest/Downloads/./packager-osx-x64
zsh: abort      ./packager-osx-x64 -version
```

I also tested v3.0.0 and got the same message. (but Mac OS X version in second line was 12.7.)
I think we need to add a compiler flag to support older macOS.

**Comment by cosmin** [comment]
Do you happen to know what that compiler flag is?

**Comment by ShimYama** [comment]
I use `-mmacosx-version-min=[version number]` flag in Makefile for my other projects.

**Comment by cosmin** [comment]
@joeyparrish any opinions on what the minimum version number we should target for MacOS?
